### ISSUE TITLE
Bug when launcing Meteor

### ISSUE THREAD

**Issue by MelonMax** [dtube/dtube#56]
I keep launching meteor and this error message. Please help. Thanks!

/Users/damianszymanski/Leaf-Tube/dtube-master/.meteor/local/build/programs/server/boot.js:475
}).run();
   ^

Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.require (/Users/damianszymanski/Leaf-Tube/dtube-master/.meteor/local/build/programs/server/boot.js:288:32)
    at makeInstallerOptions.fallback (packages/modules-runtime.js:653:18)
    at require (packages/modules-runtime.js:244:16)
    at livedata_connection.js (/Users/damianszymanski/Leaf-Tube/dtube-master/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at namespace.js (packages/ddp-client/common/namespace.js:1:300)
    at fileEvaluate (packages/modules-runtime.js:339:7)
Exited with code: 1
Your application is crashing. Waiting for file change.

**Comment by naveen-appoets** [comment]
Got the same error, kindly help.

**Comment by nobodyme** [comment]
Got the same error, kindly help.

**Comment by cryptodev90** [comment]
Run -

meteor update --release 1.7.1-beta.27
meteor npm install @babel/runtime@latest

It will solve your issue

**Comment by nobodyme** [comment]
That solved the issue for me, thanks!
